name: Develop Branch Trigger

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: mvn install

    - name: Run tests
      run: mvn test

    - name: Compile and run
      run: |
        javac HelloWorld.java
        java HelloWorld

  auto-merge:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Auto-merge pull request
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin -m
        fi

  issue-status-change:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Pull Request Number
      run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      
    - name: Extract Linked Issue URL
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        ISSUE_URL=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json body --jq '.body' | grep -o 'https://github.com/.*/issues/[0-9]*')
          echo "Issue URL: $ISSUE_URL"

    - name: Move linked issue to Ready
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        ISSUE_URL=$(gh pr view "$PR_NUMBER" --json body --jq '.body' | grep -o 'https://github.com/.*/issues/[0-9]*')
        if [ -n "$ISSUE_URL" ]; then
          ISSUE_NUMBER=$(echo $ISSUE_URL | grep -o '[0-9]*$')
          gh issue edit $ISSUE_NUMBER --add-label "Ready" --remove-label "In-Progress"
        fi